# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.30.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
        args: ['--style', '{based_on_style: pep8; indent_width: 4}']

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'  # Use the sha / tag you want to point at
    hooks:
    -   id: flake8
        args: ['--ignore=E125,E126,F401,E501,W503,W504']
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: bandit
        args: ['--skip', 'B320,B404,B410,B603', '--level', 'LOW']

-   repo: https://github.com/twu/skjold
    rev: 'v0.1.6'
    hooks:
    -   id: skjold
        args: ['-s', 'gemnasium', '-s', 'pyup']
